language: R
## reference: http://docs.travis-ci.com/user/languages/r/

language: r
r:
  - bioc-devel

cache: packages
bioc_required: true
bioc_use_devel: true

os:
  - linux
  - osx

env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=False
    - R_LIBS="http://cran.rstudio.com"

r_packages:
    - knitr
    - rmarkdown
    - covr

## bioc_packages:
##     - org.Hs.eg.db
##     - DOSE
##     - GOSemSim

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - Rscript -e 'library(ChipSeq);'

notifications:
  email:
    recipients: axy148@miami.edu    
    on_success: never
    on_failure: always

# uncomment and edit the following line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec